//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by defaulter-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&Gitlab{}, func(obj interface{}) { SetObjectDefaults_Gitlab(obj.(*Gitlab)) })
	scheme.AddTypeDefaultingFunc(&GitlabList{}, func(obj interface{}) { SetObjectDefaults_GitlabList(obj.(*GitlabList)) })
	return nil
}

func SetObjectDefaults_Gitlab(in *Gitlab) {
	SetDefaults_Gitlab(in)
}

func SetObjectDefaults_GitlabList(in *GitlabList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_Gitlab(a)
	}
}
