//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1

import (
	unsafe "unsafe"

	devops "github.com/solid-wang/covid/pkg/apis/devops"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ContinuousDeployment)(nil), (*devops.ContinuousDeployment)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ContinuousDeployment_To_devops_ContinuousDeployment(a.(*ContinuousDeployment), b.(*devops.ContinuousDeployment), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*devops.ContinuousDeployment)(nil), (*ContinuousDeployment)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_devops_ContinuousDeployment_To_v1_ContinuousDeployment(a.(*devops.ContinuousDeployment), b.(*ContinuousDeployment), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ContinuousDeploymentList)(nil), (*devops.ContinuousDeploymentList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ContinuousDeploymentList_To_devops_ContinuousDeploymentList(a.(*ContinuousDeploymentList), b.(*devops.ContinuousDeploymentList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*devops.ContinuousDeploymentList)(nil), (*ContinuousDeploymentList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_devops_ContinuousDeploymentList_To_v1_ContinuousDeploymentList(a.(*devops.ContinuousDeploymentList), b.(*ContinuousDeploymentList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ContinuousDeploymentSpec)(nil), (*devops.ContinuousDeploymentSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ContinuousDeploymentSpec_To_devops_ContinuousDeploymentSpec(a.(*ContinuousDeploymentSpec), b.(*devops.ContinuousDeploymentSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*devops.ContinuousDeploymentSpec)(nil), (*ContinuousDeploymentSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_devops_ContinuousDeploymentSpec_To_v1_ContinuousDeploymentSpec(a.(*devops.ContinuousDeploymentSpec), b.(*ContinuousDeploymentSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ContinuousDeploymentStatus)(nil), (*devops.ContinuousDeploymentStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ContinuousDeploymentStatus_To_devops_ContinuousDeploymentStatus(a.(*ContinuousDeploymentStatus), b.(*devops.ContinuousDeploymentStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*devops.ContinuousDeploymentStatus)(nil), (*ContinuousDeploymentStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_devops_ContinuousDeploymentStatus_To_v1_ContinuousDeploymentStatus(a.(*devops.ContinuousDeploymentStatus), b.(*ContinuousDeploymentStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ContinuousIntegration)(nil), (*devops.ContinuousIntegration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ContinuousIntegration_To_devops_ContinuousIntegration(a.(*ContinuousIntegration), b.(*devops.ContinuousIntegration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*devops.ContinuousIntegration)(nil), (*ContinuousIntegration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_devops_ContinuousIntegration_To_v1_ContinuousIntegration(a.(*devops.ContinuousIntegration), b.(*ContinuousIntegration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ContinuousIntegrationList)(nil), (*devops.ContinuousIntegrationList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ContinuousIntegrationList_To_devops_ContinuousIntegrationList(a.(*ContinuousIntegrationList), b.(*devops.ContinuousIntegrationList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*devops.ContinuousIntegrationList)(nil), (*ContinuousIntegrationList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_devops_ContinuousIntegrationList_To_v1_ContinuousIntegrationList(a.(*devops.ContinuousIntegrationList), b.(*ContinuousIntegrationList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ContinuousIntegrationSpec)(nil), (*devops.ContinuousIntegrationSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ContinuousIntegrationSpec_To_devops_ContinuousIntegrationSpec(a.(*ContinuousIntegrationSpec), b.(*devops.ContinuousIntegrationSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*devops.ContinuousIntegrationSpec)(nil), (*ContinuousIntegrationSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_devops_ContinuousIntegrationSpec_To_v1_ContinuousIntegrationSpec(a.(*devops.ContinuousIntegrationSpec), b.(*ContinuousIntegrationSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ContinuousIntegrationStatus)(nil), (*devops.ContinuousIntegrationStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ContinuousIntegrationStatus_To_devops_ContinuousIntegrationStatus(a.(*ContinuousIntegrationStatus), b.(*devops.ContinuousIntegrationStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*devops.ContinuousIntegrationStatus)(nil), (*ContinuousIntegrationStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_devops_ContinuousIntegrationStatus_To_v1_ContinuousIntegrationStatus(a.(*devops.ContinuousIntegrationStatus), b.(*ContinuousIntegrationStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Deploy)(nil), (*devops.Deploy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Deploy_To_devops_Deploy(a.(*Deploy), b.(*devops.Deploy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*devops.Deploy)(nil), (*Deploy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_devops_Deploy_To_v1_Deploy(a.(*devops.Deploy), b.(*Deploy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Deploying)(nil), (*devops.Deploying)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Deploying_To_devops_Deploying(a.(*Deploying), b.(*devops.Deploying), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*devops.Deploying)(nil), (*Deploying)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_devops_Deploying_To_v1_Deploying(a.(*devops.Deploying), b.(*Deploying), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1_ContinuousDeployment_To_devops_ContinuousDeployment(in *ContinuousDeployment, out *devops.ContinuousDeployment, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_ContinuousDeploymentSpec_To_devops_ContinuousDeploymentSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_ContinuousDeploymentStatus_To_devops_ContinuousDeploymentStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_ContinuousDeployment_To_devops_ContinuousDeployment is an autogenerated conversion function.
func Convert_v1_ContinuousDeployment_To_devops_ContinuousDeployment(in *ContinuousDeployment, out *devops.ContinuousDeployment, s conversion.Scope) error {
	return autoConvert_v1_ContinuousDeployment_To_devops_ContinuousDeployment(in, out, s)
}

func autoConvert_devops_ContinuousDeployment_To_v1_ContinuousDeployment(in *devops.ContinuousDeployment, out *ContinuousDeployment, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_devops_ContinuousDeploymentSpec_To_v1_ContinuousDeploymentSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_devops_ContinuousDeploymentStatus_To_v1_ContinuousDeploymentStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_devops_ContinuousDeployment_To_v1_ContinuousDeployment is an autogenerated conversion function.
func Convert_devops_ContinuousDeployment_To_v1_ContinuousDeployment(in *devops.ContinuousDeployment, out *ContinuousDeployment, s conversion.Scope) error {
	return autoConvert_devops_ContinuousDeployment_To_v1_ContinuousDeployment(in, out, s)
}

func autoConvert_v1_ContinuousDeploymentList_To_devops_ContinuousDeploymentList(in *ContinuousDeploymentList, out *devops.ContinuousDeploymentList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]devops.ContinuousDeployment)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_ContinuousDeploymentList_To_devops_ContinuousDeploymentList is an autogenerated conversion function.
func Convert_v1_ContinuousDeploymentList_To_devops_ContinuousDeploymentList(in *ContinuousDeploymentList, out *devops.ContinuousDeploymentList, s conversion.Scope) error {
	return autoConvert_v1_ContinuousDeploymentList_To_devops_ContinuousDeploymentList(in, out, s)
}

func autoConvert_devops_ContinuousDeploymentList_To_v1_ContinuousDeploymentList(in *devops.ContinuousDeploymentList, out *ContinuousDeploymentList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]ContinuousDeployment)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_devops_ContinuousDeploymentList_To_v1_ContinuousDeploymentList is an autogenerated conversion function.
func Convert_devops_ContinuousDeploymentList_To_v1_ContinuousDeploymentList(in *devops.ContinuousDeploymentList, out *ContinuousDeploymentList, s conversion.Scope) error {
	return autoConvert_devops_ContinuousDeploymentList_To_v1_ContinuousDeploymentList(in, out, s)
}

func autoConvert_v1_ContinuousDeploymentSpec_To_devops_ContinuousDeploymentSpec(in *ContinuousDeploymentSpec, out *devops.ContinuousDeploymentSpec, s conversion.Scope) error {
	out.ManifestRepo = in.ManifestRepo
	out.EnvDeployMap = *(*map[string]devops.Deploy)(unsafe.Pointer(&in.EnvDeployMap))
	return nil
}

// Convert_v1_ContinuousDeploymentSpec_To_devops_ContinuousDeploymentSpec is an autogenerated conversion function.
func Convert_v1_ContinuousDeploymentSpec_To_devops_ContinuousDeploymentSpec(in *ContinuousDeploymentSpec, out *devops.ContinuousDeploymentSpec, s conversion.Scope) error {
	return autoConvert_v1_ContinuousDeploymentSpec_To_devops_ContinuousDeploymentSpec(in, out, s)
}

func autoConvert_devops_ContinuousDeploymentSpec_To_v1_ContinuousDeploymentSpec(in *devops.ContinuousDeploymentSpec, out *ContinuousDeploymentSpec, s conversion.Scope) error {
	out.ManifestRepo = in.ManifestRepo
	out.EnvDeployMap = *(*map[string]Deploy)(unsafe.Pointer(&in.EnvDeployMap))
	return nil
}

// Convert_devops_ContinuousDeploymentSpec_To_v1_ContinuousDeploymentSpec is an autogenerated conversion function.
func Convert_devops_ContinuousDeploymentSpec_To_v1_ContinuousDeploymentSpec(in *devops.ContinuousDeploymentSpec, out *ContinuousDeploymentSpec, s conversion.Scope) error {
	return autoConvert_devops_ContinuousDeploymentSpec_To_v1_ContinuousDeploymentSpec(in, out, s)
}

func autoConvert_v1_ContinuousDeploymentStatus_To_devops_ContinuousDeploymentStatus(in *ContinuousDeploymentStatus, out *devops.ContinuousDeploymentStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1_ContinuousDeploymentStatus_To_devops_ContinuousDeploymentStatus is an autogenerated conversion function.
func Convert_v1_ContinuousDeploymentStatus_To_devops_ContinuousDeploymentStatus(in *ContinuousDeploymentStatus, out *devops.ContinuousDeploymentStatus, s conversion.Scope) error {
	return autoConvert_v1_ContinuousDeploymentStatus_To_devops_ContinuousDeploymentStatus(in, out, s)
}

func autoConvert_devops_ContinuousDeploymentStatus_To_v1_ContinuousDeploymentStatus(in *devops.ContinuousDeploymentStatus, out *ContinuousDeploymentStatus, s conversion.Scope) error {
	return nil
}

// Convert_devops_ContinuousDeploymentStatus_To_v1_ContinuousDeploymentStatus is an autogenerated conversion function.
func Convert_devops_ContinuousDeploymentStatus_To_v1_ContinuousDeploymentStatus(in *devops.ContinuousDeploymentStatus, out *ContinuousDeploymentStatus, s conversion.Scope) error {
	return autoConvert_devops_ContinuousDeploymentStatus_To_v1_ContinuousDeploymentStatus(in, out, s)
}

func autoConvert_v1_ContinuousIntegration_To_devops_ContinuousIntegration(in *ContinuousIntegration, out *devops.ContinuousIntegration, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_ContinuousIntegrationSpec_To_devops_ContinuousIntegrationSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_ContinuousIntegrationStatus_To_devops_ContinuousIntegrationStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_ContinuousIntegration_To_devops_ContinuousIntegration is an autogenerated conversion function.
func Convert_v1_ContinuousIntegration_To_devops_ContinuousIntegration(in *ContinuousIntegration, out *devops.ContinuousIntegration, s conversion.Scope) error {
	return autoConvert_v1_ContinuousIntegration_To_devops_ContinuousIntegration(in, out, s)
}

func autoConvert_devops_ContinuousIntegration_To_v1_ContinuousIntegration(in *devops.ContinuousIntegration, out *ContinuousIntegration, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_devops_ContinuousIntegrationSpec_To_v1_ContinuousIntegrationSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_devops_ContinuousIntegrationStatus_To_v1_ContinuousIntegrationStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_devops_ContinuousIntegration_To_v1_ContinuousIntegration is an autogenerated conversion function.
func Convert_devops_ContinuousIntegration_To_v1_ContinuousIntegration(in *devops.ContinuousIntegration, out *ContinuousIntegration, s conversion.Scope) error {
	return autoConvert_devops_ContinuousIntegration_To_v1_ContinuousIntegration(in, out, s)
}

func autoConvert_v1_ContinuousIntegrationList_To_devops_ContinuousIntegrationList(in *ContinuousIntegrationList, out *devops.ContinuousIntegrationList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]devops.ContinuousIntegration)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_ContinuousIntegrationList_To_devops_ContinuousIntegrationList is an autogenerated conversion function.
func Convert_v1_ContinuousIntegrationList_To_devops_ContinuousIntegrationList(in *ContinuousIntegrationList, out *devops.ContinuousIntegrationList, s conversion.Scope) error {
	return autoConvert_v1_ContinuousIntegrationList_To_devops_ContinuousIntegrationList(in, out, s)
}

func autoConvert_devops_ContinuousIntegrationList_To_v1_ContinuousIntegrationList(in *devops.ContinuousIntegrationList, out *ContinuousIntegrationList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]ContinuousIntegration)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_devops_ContinuousIntegrationList_To_v1_ContinuousIntegrationList is an autogenerated conversion function.
func Convert_devops_ContinuousIntegrationList_To_v1_ContinuousIntegrationList(in *devops.ContinuousIntegrationList, out *ContinuousIntegrationList, s conversion.Scope) error {
	return autoConvert_devops_ContinuousIntegrationList_To_v1_ContinuousIntegrationList(in, out, s)
}

func autoConvert_v1_ContinuousIntegrationSpec_To_devops_ContinuousIntegrationSpec(in *ContinuousIntegrationSpec, out *devops.ContinuousIntegrationSpec, s conversion.Scope) error {
	out.CIConfigPath = in.CIConfigPath
	out.BuildImage = in.BuildImage
	out.FromImage = in.FromImage
	out.BuildDir = in.BuildDir
	out.BuildCommand = in.BuildCommand
	out.ArtifactPath = in.ArtifactPath
	out.Image = in.Image
	out.BuiltCommitHistory = *(*[]devops.CodeCommit)(unsafe.Pointer(&in.BuiltCommitHistory))
	return nil
}

// Convert_v1_ContinuousIntegrationSpec_To_devops_ContinuousIntegrationSpec is an autogenerated conversion function.
func Convert_v1_ContinuousIntegrationSpec_To_devops_ContinuousIntegrationSpec(in *ContinuousIntegrationSpec, out *devops.ContinuousIntegrationSpec, s conversion.Scope) error {
	return autoConvert_v1_ContinuousIntegrationSpec_To_devops_ContinuousIntegrationSpec(in, out, s)
}

func autoConvert_devops_ContinuousIntegrationSpec_To_v1_ContinuousIntegrationSpec(in *devops.ContinuousIntegrationSpec, out *ContinuousIntegrationSpec, s conversion.Scope) error {
	out.CIConfigPath = in.CIConfigPath
	out.BuildImage = in.BuildImage
	out.FromImage = in.FromImage
	out.BuildDir = in.BuildDir
	out.BuildCommand = in.BuildCommand
	out.ArtifactPath = in.ArtifactPath
	out.Image = in.Image
	out.BuiltCommitHistory = *(*[]CodeCommit)(unsafe.Pointer(&in.BuiltCommitHistory))
	return nil
}

// Convert_devops_ContinuousIntegrationSpec_To_v1_ContinuousIntegrationSpec is an autogenerated conversion function.
func Convert_devops_ContinuousIntegrationSpec_To_v1_ContinuousIntegrationSpec(in *devops.ContinuousIntegrationSpec, out *ContinuousIntegrationSpec, s conversion.Scope) error {
	return autoConvert_devops_ContinuousIntegrationSpec_To_v1_ContinuousIntegrationSpec(in, out, s)
}

func autoConvert_v1_ContinuousIntegrationStatus_To_devops_ContinuousIntegrationStatus(in *ContinuousIntegrationStatus, out *devops.ContinuousIntegrationStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1_ContinuousIntegrationStatus_To_devops_ContinuousIntegrationStatus is an autogenerated conversion function.
func Convert_v1_ContinuousIntegrationStatus_To_devops_ContinuousIntegrationStatus(in *ContinuousIntegrationStatus, out *devops.ContinuousIntegrationStatus, s conversion.Scope) error {
	return autoConvert_v1_ContinuousIntegrationStatus_To_devops_ContinuousIntegrationStatus(in, out, s)
}

func autoConvert_devops_ContinuousIntegrationStatus_To_v1_ContinuousIntegrationStatus(in *devops.ContinuousIntegrationStatus, out *ContinuousIntegrationStatus, s conversion.Scope) error {
	return nil
}

// Convert_devops_ContinuousIntegrationStatus_To_v1_ContinuousIntegrationStatus is an autogenerated conversion function.
func Convert_devops_ContinuousIntegrationStatus_To_v1_ContinuousIntegrationStatus(in *devops.ContinuousIntegrationStatus, out *ContinuousIntegrationStatus, s conversion.Scope) error {
	return autoConvert_devops_ContinuousIntegrationStatus_To_v1_ContinuousIntegrationStatus(in, out, s)
}

func autoConvert_v1_Deploy_To_devops_Deploy(in *Deploy, out *devops.Deploy, s conversion.Scope) error {
	out.Approval = in.Approval
	out.KubernetesName = in.KubernetesName
	out.KubernetesNamespace = in.KubernetesNamespace
	out.DeployedManifestCommit = in.DeployedManifestCommit
	if err := Convert_v1_Deploying_To_devops_Deploying(&in.Deploying, &out.Deploying, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_Deploy_To_devops_Deploy is an autogenerated conversion function.
func Convert_v1_Deploy_To_devops_Deploy(in *Deploy, out *devops.Deploy, s conversion.Scope) error {
	return autoConvert_v1_Deploy_To_devops_Deploy(in, out, s)
}

func autoConvert_devops_Deploy_To_v1_Deploy(in *devops.Deploy, out *Deploy, s conversion.Scope) error {
	out.Approval = in.Approval
	out.KubernetesName = in.KubernetesName
	out.KubernetesNamespace = in.KubernetesNamespace
	out.DeployedManifestCommit = in.DeployedManifestCommit
	if err := Convert_devops_Deploying_To_v1_Deploying(&in.Deploying, &out.Deploying, s); err != nil {
		return err
	}
	return nil
}

// Convert_devops_Deploy_To_v1_Deploy is an autogenerated conversion function.
func Convert_devops_Deploy_To_v1_Deploy(in *devops.Deploy, out *Deploy, s conversion.Scope) error {
	return autoConvert_devops_Deploy_To_v1_Deploy(in, out, s)
}

func autoConvert_v1_Deploying_To_devops_Deploying(in *Deploying, out *devops.Deploying, s conversion.Scope) error {
	out.ManifestCommit = devops.ManifestCommit(in.ManifestCommit)
	out.ApprovalInstanceCode = in.ApprovalInstanceCode
	return nil
}

// Convert_v1_Deploying_To_devops_Deploying is an autogenerated conversion function.
func Convert_v1_Deploying_To_devops_Deploying(in *Deploying, out *devops.Deploying, s conversion.Scope) error {
	return autoConvert_v1_Deploying_To_devops_Deploying(in, out, s)
}

func autoConvert_devops_Deploying_To_v1_Deploying(in *devops.Deploying, out *Deploying, s conversion.Scope) error {
	out.ManifestCommit = ManifestCommit(in.ManifestCommit)
	out.ApprovalInstanceCode = in.ApprovalInstanceCode
	return nil
}

// Convert_devops_Deploying_To_v1_Deploying is an autogenerated conversion function.
func Convert_devops_Deploying_To_v1_Deploying(in *devops.Deploying, out *Deploying, s conversion.Scope) error {
	return autoConvert_devops_Deploying_To_v1_Deploying(in, out, s)
}
