//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContinuousDeployment) DeepCopyInto(out *ContinuousDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContinuousDeployment.
func (in *ContinuousDeployment) DeepCopy() *ContinuousDeployment {
	if in == nil {
		return nil
	}
	out := new(ContinuousDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContinuousDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContinuousDeploymentList) DeepCopyInto(out *ContinuousDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ContinuousDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContinuousDeploymentList.
func (in *ContinuousDeploymentList) DeepCopy() *ContinuousDeploymentList {
	if in == nil {
		return nil
	}
	out := new(ContinuousDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContinuousDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContinuousDeploymentSpec) DeepCopyInto(out *ContinuousDeploymentSpec) {
	*out = *in
	if in.EnvDeployMap != nil {
		in, out := &in.EnvDeployMap, &out.EnvDeployMap
		*out = make(map[string]Deploy, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContinuousDeploymentSpec.
func (in *ContinuousDeploymentSpec) DeepCopy() *ContinuousDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(ContinuousDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContinuousDeploymentStatus) DeepCopyInto(out *ContinuousDeploymentStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContinuousDeploymentStatus.
func (in *ContinuousDeploymentStatus) DeepCopy() *ContinuousDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(ContinuousDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContinuousIntegration) DeepCopyInto(out *ContinuousIntegration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContinuousIntegration.
func (in *ContinuousIntegration) DeepCopy() *ContinuousIntegration {
	if in == nil {
		return nil
	}
	out := new(ContinuousIntegration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContinuousIntegration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContinuousIntegrationList) DeepCopyInto(out *ContinuousIntegrationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ContinuousIntegration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContinuousIntegrationList.
func (in *ContinuousIntegrationList) DeepCopy() *ContinuousIntegrationList {
	if in == nil {
		return nil
	}
	out := new(ContinuousIntegrationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContinuousIntegrationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContinuousIntegrationSpec) DeepCopyInto(out *ContinuousIntegrationSpec) {
	*out = *in
	if in.BuiltCommitHistory != nil {
		in, out := &in.BuiltCommitHistory, &out.BuiltCommitHistory
		*out = make([]CodeCommit, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContinuousIntegrationSpec.
func (in *ContinuousIntegrationSpec) DeepCopy() *ContinuousIntegrationSpec {
	if in == nil {
		return nil
	}
	out := new(ContinuousIntegrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContinuousIntegrationStatus) DeepCopyInto(out *ContinuousIntegrationStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContinuousIntegrationStatus.
func (in *ContinuousIntegrationStatus) DeepCopy() *ContinuousIntegrationStatus {
	if in == nil {
		return nil
	}
	out := new(ContinuousIntegrationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Deploy) DeepCopyInto(out *Deploy) {
	*out = *in
	out.Deploying = in.Deploying
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Deploy.
func (in *Deploy) DeepCopy() *Deploy {
	if in == nil {
		return nil
	}
	out := new(Deploy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Deploying) DeepCopyInto(out *Deploying) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Deploying.
func (in *Deploying) DeepCopy() *Deploying {
	if in == nil {
		return nil
	}
	out := new(Deploying)
	in.DeepCopyInto(out)
	return out
}
