//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1

import (
	unsafe "unsafe"

	example "github.com/solid-wang/covid/pkg/apis/example"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Demo1)(nil), (*example.Demo1)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Demo1_To_example_Demo1(a.(*Demo1), b.(*example.Demo1), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*example.Demo1)(nil), (*Demo1)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_example_Demo1_To_v1_Demo1(a.(*example.Demo1), b.(*Demo1), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Demo1List)(nil), (*example.Demo1List)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Demo1List_To_example_Demo1List(a.(*Demo1List), b.(*example.Demo1List), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*example.Demo1List)(nil), (*Demo1List)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_example_Demo1List_To_v1_Demo1List(a.(*example.Demo1List), b.(*Demo1List), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Demo1Spec)(nil), (*example.Demo1Spec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Demo1Spec_To_example_Demo1Spec(a.(*Demo1Spec), b.(*example.Demo1Spec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*example.Demo1Spec)(nil), (*Demo1Spec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_example_Demo1Spec_To_v1_Demo1Spec(a.(*example.Demo1Spec), b.(*Demo1Spec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Demo1Status)(nil), (*example.Demo1Status)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Demo1Status_To_example_Demo1Status(a.(*Demo1Status), b.(*example.Demo1Status), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*example.Demo1Status)(nil), (*Demo1Status)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_example_Demo1Status_To_v1_Demo1Status(a.(*example.Demo1Status), b.(*Demo1Status), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1_Demo1_To_example_Demo1(in *Demo1, out *example.Demo1, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_Demo1Spec_To_example_Demo1Spec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_Demo1Status_To_example_Demo1Status(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_Demo1_To_example_Demo1 is an autogenerated conversion function.
func Convert_v1_Demo1_To_example_Demo1(in *Demo1, out *example.Demo1, s conversion.Scope) error {
	return autoConvert_v1_Demo1_To_example_Demo1(in, out, s)
}

func autoConvert_example_Demo1_To_v1_Demo1(in *example.Demo1, out *Demo1, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_example_Demo1Spec_To_v1_Demo1Spec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_example_Demo1Status_To_v1_Demo1Status(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_example_Demo1_To_v1_Demo1 is an autogenerated conversion function.
func Convert_example_Demo1_To_v1_Demo1(in *example.Demo1, out *Demo1, s conversion.Scope) error {
	return autoConvert_example_Demo1_To_v1_Demo1(in, out, s)
}

func autoConvert_v1_Demo1List_To_example_Demo1List(in *Demo1List, out *example.Demo1List, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]example.Demo1)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_Demo1List_To_example_Demo1List is an autogenerated conversion function.
func Convert_v1_Demo1List_To_example_Demo1List(in *Demo1List, out *example.Demo1List, s conversion.Scope) error {
	return autoConvert_v1_Demo1List_To_example_Demo1List(in, out, s)
}

func autoConvert_example_Demo1List_To_v1_Demo1List(in *example.Demo1List, out *Demo1List, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Demo1)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_example_Demo1List_To_v1_Demo1List is an autogenerated conversion function.
func Convert_example_Demo1List_To_v1_Demo1List(in *example.Demo1List, out *Demo1List, s conversion.Scope) error {
	return autoConvert_example_Demo1List_To_v1_Demo1List(in, out, s)
}

func autoConvert_v1_Demo1Spec_To_example_Demo1Spec(in *Demo1Spec, out *example.Demo1Spec, s conversion.Scope) error {
	out.V1 = in.V1
	return nil
}

// Convert_v1_Demo1Spec_To_example_Demo1Spec is an autogenerated conversion function.
func Convert_v1_Demo1Spec_To_example_Demo1Spec(in *Demo1Spec, out *example.Demo1Spec, s conversion.Scope) error {
	return autoConvert_v1_Demo1Spec_To_example_Demo1Spec(in, out, s)
}

func autoConvert_example_Demo1Spec_To_v1_Demo1Spec(in *example.Demo1Spec, out *Demo1Spec, s conversion.Scope) error {
	out.V1 = in.V1
	return nil
}

// Convert_example_Demo1Spec_To_v1_Demo1Spec is an autogenerated conversion function.
func Convert_example_Demo1Spec_To_v1_Demo1Spec(in *example.Demo1Spec, out *Demo1Spec, s conversion.Scope) error {
	return autoConvert_example_Demo1Spec_To_v1_Demo1Spec(in, out, s)
}

func autoConvert_v1_Demo1Status_To_example_Demo1Status(in *Demo1Status, out *example.Demo1Status, s conversion.Scope) error {
	return nil
}

// Convert_v1_Demo1Status_To_example_Demo1Status is an autogenerated conversion function.
func Convert_v1_Demo1Status_To_example_Demo1Status(in *Demo1Status, out *example.Demo1Status, s conversion.Scope) error {
	return autoConvert_v1_Demo1Status_To_example_Demo1Status(in, out, s)
}

func autoConvert_example_Demo1Status_To_v1_Demo1Status(in *example.Demo1Status, out *Demo1Status, s conversion.Scope) error {
	return nil
}

// Convert_example_Demo1Status_To_v1_Demo1Status is an autogenerated conversion function.
func Convert_example_Demo1Status_To_v1_Demo1Status(in *example.Demo1Status, out *Demo1Status, s conversion.Scope) error {
	return autoConvert_example_Demo1Status_To_v1_Demo1Status(in, out, s)
}
