//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1

import (
	unsafe "unsafe"

	cmdb "github.com/solid-wang/covid/pkg/apis/cmdb"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ContinuousDeploymentInfo)(nil), (*cmdb.ContinuousDeploymentInfo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ContinuousDeploymentInfo_To_cmdb_ContinuousDeploymentInfo(a.(*ContinuousDeploymentInfo), b.(*cmdb.ContinuousDeploymentInfo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cmdb.ContinuousDeploymentInfo)(nil), (*ContinuousDeploymentInfo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cmdb_ContinuousDeploymentInfo_To_v1_ContinuousDeploymentInfo(a.(*cmdb.ContinuousDeploymentInfo), b.(*ContinuousDeploymentInfo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ContinuousIntegrationInfo)(nil), (*cmdb.ContinuousIntegrationInfo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ContinuousIntegrationInfo_To_cmdb_ContinuousIntegrationInfo(a.(*ContinuousIntegrationInfo), b.(*cmdb.ContinuousIntegrationInfo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cmdb.ContinuousIntegrationInfo)(nil), (*ContinuousIntegrationInfo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cmdb_ContinuousIntegrationInfo_To_v1_ContinuousIntegrationInfo(a.(*cmdb.ContinuousIntegrationInfo), b.(*ContinuousIntegrationInfo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DockerRepository)(nil), (*cmdb.DockerRepository)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_DockerRepository_To_cmdb_DockerRepository(a.(*DockerRepository), b.(*cmdb.DockerRepository), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cmdb.DockerRepository)(nil), (*DockerRepository)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cmdb_DockerRepository_To_v1_DockerRepository(a.(*cmdb.DockerRepository), b.(*DockerRepository), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DockerRepositoryList)(nil), (*cmdb.DockerRepositoryList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_DockerRepositoryList_To_cmdb_DockerRepositoryList(a.(*DockerRepositoryList), b.(*cmdb.DockerRepositoryList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cmdb.DockerRepositoryList)(nil), (*DockerRepositoryList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cmdb_DockerRepositoryList_To_v1_DockerRepositoryList(a.(*cmdb.DockerRepositoryList), b.(*DockerRepositoryList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DockerRepositorySpec)(nil), (*cmdb.DockerRepositorySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_DockerRepositorySpec_To_cmdb_DockerRepositorySpec(a.(*DockerRepositorySpec), b.(*cmdb.DockerRepositorySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cmdb.DockerRepositorySpec)(nil), (*DockerRepositorySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cmdb_DockerRepositorySpec_To_v1_DockerRepositorySpec(a.(*cmdb.DockerRepositorySpec), b.(*DockerRepositorySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DockerRepositoryStatus)(nil), (*cmdb.DockerRepositoryStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_DockerRepositoryStatus_To_cmdb_DockerRepositoryStatus(a.(*DockerRepositoryStatus), b.(*cmdb.DockerRepositoryStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cmdb.DockerRepositoryStatus)(nil), (*DockerRepositoryStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cmdb_DockerRepositoryStatus_To_v1_DockerRepositoryStatus(a.(*cmdb.DockerRepositoryStatus), b.(*DockerRepositoryStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*EnvInfo)(nil), (*cmdb.EnvInfo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_EnvInfo_To_cmdb_EnvInfo(a.(*EnvInfo), b.(*cmdb.EnvInfo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cmdb.EnvInfo)(nil), (*EnvInfo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cmdb_EnvInfo_To_v1_EnvInfo(a.(*cmdb.EnvInfo), b.(*EnvInfo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FeiShuApp)(nil), (*cmdb.FeiShuApp)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_FeiShuApp_To_cmdb_FeiShuApp(a.(*FeiShuApp), b.(*cmdb.FeiShuApp), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cmdb.FeiShuApp)(nil), (*FeiShuApp)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cmdb_FeiShuApp_To_v1_FeiShuApp(a.(*cmdb.FeiShuApp), b.(*FeiShuApp), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FeiShuAppList)(nil), (*cmdb.FeiShuAppList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_FeiShuAppList_To_cmdb_FeiShuAppList(a.(*FeiShuAppList), b.(*cmdb.FeiShuAppList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cmdb.FeiShuAppList)(nil), (*FeiShuAppList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cmdb_FeiShuAppList_To_v1_FeiShuAppList(a.(*cmdb.FeiShuAppList), b.(*FeiShuAppList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FeiShuAppSpec)(nil), (*cmdb.FeiShuAppSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_FeiShuAppSpec_To_cmdb_FeiShuAppSpec(a.(*FeiShuAppSpec), b.(*cmdb.FeiShuAppSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cmdb.FeiShuAppSpec)(nil), (*FeiShuAppSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cmdb_FeiShuAppSpec_To_v1_FeiShuAppSpec(a.(*cmdb.FeiShuAppSpec), b.(*FeiShuAppSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FeiShuAppStatus)(nil), (*cmdb.FeiShuAppStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_FeiShuAppStatus_To_cmdb_FeiShuAppStatus(a.(*FeiShuAppStatus), b.(*cmdb.FeiShuAppStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cmdb.FeiShuAppStatus)(nil), (*FeiShuAppStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cmdb_FeiShuAppStatus_To_v1_FeiShuAppStatus(a.(*cmdb.FeiShuAppStatus), b.(*FeiShuAppStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Gitlab)(nil), (*cmdb.Gitlab)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Gitlab_To_cmdb_Gitlab(a.(*Gitlab), b.(*cmdb.Gitlab), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cmdb.Gitlab)(nil), (*Gitlab)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cmdb_Gitlab_To_v1_Gitlab(a.(*cmdb.Gitlab), b.(*Gitlab), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GitlabInfo)(nil), (*cmdb.GitlabInfo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_GitlabInfo_To_cmdb_GitlabInfo(a.(*GitlabInfo), b.(*cmdb.GitlabInfo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cmdb.GitlabInfo)(nil), (*GitlabInfo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cmdb_GitlabInfo_To_v1_GitlabInfo(a.(*cmdb.GitlabInfo), b.(*GitlabInfo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GitlabList)(nil), (*cmdb.GitlabList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_GitlabList_To_cmdb_GitlabList(a.(*GitlabList), b.(*cmdb.GitlabList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cmdb.GitlabList)(nil), (*GitlabList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cmdb_GitlabList_To_v1_GitlabList(a.(*cmdb.GitlabList), b.(*GitlabList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GitlabSpec)(nil), (*cmdb.GitlabSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_GitlabSpec_To_cmdb_GitlabSpec(a.(*GitlabSpec), b.(*cmdb.GitlabSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cmdb.GitlabSpec)(nil), (*GitlabSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cmdb_GitlabSpec_To_v1_GitlabSpec(a.(*cmdb.GitlabSpec), b.(*GitlabSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GitlabStatus)(nil), (*cmdb.GitlabStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_GitlabStatus_To_cmdb_GitlabStatus(a.(*GitlabStatus), b.(*cmdb.GitlabStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cmdb.GitlabStatus)(nil), (*GitlabStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cmdb_GitlabStatus_To_v1_GitlabStatus(a.(*cmdb.GitlabStatus), b.(*GitlabStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Kubernetes)(nil), (*cmdb.Kubernetes)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Kubernetes_To_cmdb_Kubernetes(a.(*Kubernetes), b.(*cmdb.Kubernetes), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cmdb.Kubernetes)(nil), (*Kubernetes)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cmdb_Kubernetes_To_v1_Kubernetes(a.(*cmdb.Kubernetes), b.(*Kubernetes), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*KubernetesInfo)(nil), (*cmdb.KubernetesInfo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_KubernetesInfo_To_cmdb_KubernetesInfo(a.(*KubernetesInfo), b.(*cmdb.KubernetesInfo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cmdb.KubernetesInfo)(nil), (*KubernetesInfo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cmdb_KubernetesInfo_To_v1_KubernetesInfo(a.(*cmdb.KubernetesInfo), b.(*KubernetesInfo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*KubernetesList)(nil), (*cmdb.KubernetesList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_KubernetesList_To_cmdb_KubernetesList(a.(*KubernetesList), b.(*cmdb.KubernetesList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cmdb.KubernetesList)(nil), (*KubernetesList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cmdb_KubernetesList_To_v1_KubernetesList(a.(*cmdb.KubernetesList), b.(*KubernetesList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*KubernetesSpec)(nil), (*cmdb.KubernetesSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_KubernetesSpec_To_cmdb_KubernetesSpec(a.(*KubernetesSpec), b.(*cmdb.KubernetesSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cmdb.KubernetesSpec)(nil), (*KubernetesSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cmdb_KubernetesSpec_To_v1_KubernetesSpec(a.(*cmdb.KubernetesSpec), b.(*KubernetesSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*KubernetesStatus)(nil), (*cmdb.KubernetesStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_KubernetesStatus_To_cmdb_KubernetesStatus(a.(*KubernetesStatus), b.(*cmdb.KubernetesStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cmdb.KubernetesStatus)(nil), (*KubernetesStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cmdb_KubernetesStatus_To_v1_KubernetesStatus(a.(*cmdb.KubernetesStatus), b.(*KubernetesStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Product)(nil), (*cmdb.Product)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Product_To_cmdb_Product(a.(*Product), b.(*cmdb.Product), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cmdb.Product)(nil), (*Product)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cmdb_Product_To_v1_Product(a.(*cmdb.Product), b.(*Product), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProductList)(nil), (*cmdb.ProductList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ProductList_To_cmdb_ProductList(a.(*ProductList), b.(*cmdb.ProductList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cmdb.ProductList)(nil), (*ProductList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cmdb_ProductList_To_v1_ProductList(a.(*cmdb.ProductList), b.(*ProductList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProductSpec)(nil), (*cmdb.ProductSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ProductSpec_To_cmdb_ProductSpec(a.(*ProductSpec), b.(*cmdb.ProductSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cmdb.ProductSpec)(nil), (*ProductSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cmdb_ProductSpec_To_v1_ProductSpec(a.(*cmdb.ProductSpec), b.(*ProductSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProductStatus)(nil), (*cmdb.ProductStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ProductStatus_To_cmdb_ProductStatus(a.(*ProductStatus), b.(*cmdb.ProductStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cmdb.ProductStatus)(nil), (*ProductStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cmdb_ProductStatus_To_v1_ProductStatus(a.(*cmdb.ProductStatus), b.(*ProductStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Project)(nil), (*cmdb.Project)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Project_To_cmdb_Project(a.(*Project), b.(*cmdb.Project), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cmdb.Project)(nil), (*Project)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cmdb_Project_To_v1_Project(a.(*cmdb.Project), b.(*Project), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Server)(nil), (*cmdb.Server)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Server_To_cmdb_Server(a.(*Server), b.(*cmdb.Server), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cmdb.Server)(nil), (*Server)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cmdb_Server_To_v1_Server(a.(*cmdb.Server), b.(*Server), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ServerList)(nil), (*cmdb.ServerList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ServerList_To_cmdb_ServerList(a.(*ServerList), b.(*cmdb.ServerList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cmdb.ServerList)(nil), (*ServerList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cmdb_ServerList_To_v1_ServerList(a.(*cmdb.ServerList), b.(*ServerList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ServerSpec)(nil), (*cmdb.ServerSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ServerSpec_To_cmdb_ServerSpec(a.(*ServerSpec), b.(*cmdb.ServerSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cmdb.ServerSpec)(nil), (*ServerSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cmdb_ServerSpec_To_v1_ServerSpec(a.(*cmdb.ServerSpec), b.(*ServerSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ServerStatus)(nil), (*cmdb.ServerStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ServerStatus_To_cmdb_ServerStatus(a.(*ServerStatus), b.(*cmdb.ServerStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cmdb.ServerStatus)(nil), (*ServerStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cmdb_ServerStatus_To_v1_ServerStatus(a.(*cmdb.ServerStatus), b.(*ServerStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1_ContinuousDeploymentInfo_To_cmdb_ContinuousDeploymentInfo(in *ContinuousDeploymentInfo, out *cmdb.ContinuousDeploymentInfo, s conversion.Scope) error {
	out.EnvMap = *(*map[string]cmdb.EnvInfo)(unsafe.Pointer(&in.EnvMap))
	return nil
}

// Convert_v1_ContinuousDeploymentInfo_To_cmdb_ContinuousDeploymentInfo is an autogenerated conversion function.
func Convert_v1_ContinuousDeploymentInfo_To_cmdb_ContinuousDeploymentInfo(in *ContinuousDeploymentInfo, out *cmdb.ContinuousDeploymentInfo, s conversion.Scope) error {
	return autoConvert_v1_ContinuousDeploymentInfo_To_cmdb_ContinuousDeploymentInfo(in, out, s)
}

func autoConvert_cmdb_ContinuousDeploymentInfo_To_v1_ContinuousDeploymentInfo(in *cmdb.ContinuousDeploymentInfo, out *ContinuousDeploymentInfo, s conversion.Scope) error {
	out.EnvMap = *(*map[string]EnvInfo)(unsafe.Pointer(&in.EnvMap))
	return nil
}

// Convert_cmdb_ContinuousDeploymentInfo_To_v1_ContinuousDeploymentInfo is an autogenerated conversion function.
func Convert_cmdb_ContinuousDeploymentInfo_To_v1_ContinuousDeploymentInfo(in *cmdb.ContinuousDeploymentInfo, out *ContinuousDeploymentInfo, s conversion.Scope) error {
	return autoConvert_cmdb_ContinuousDeploymentInfo_To_v1_ContinuousDeploymentInfo(in, out, s)
}

func autoConvert_v1_ContinuousIntegrationInfo_To_cmdb_ContinuousIntegrationInfo(in *ContinuousIntegrationInfo, out *cmdb.ContinuousIntegrationInfo, s conversion.Scope) error {
	out.ConfigPath = in.ConfigPath
	out.BuildImage = in.BuildImage
	out.FromImage = in.FromImage
	out.BuildDir = in.BuildDir
	out.BuildCommand = in.BuildCommand
	out.ArtifactPath = in.ArtifactPath
	out.PushRepository = in.PushRepository
	return nil
}

// Convert_v1_ContinuousIntegrationInfo_To_cmdb_ContinuousIntegrationInfo is an autogenerated conversion function.
func Convert_v1_ContinuousIntegrationInfo_To_cmdb_ContinuousIntegrationInfo(in *ContinuousIntegrationInfo, out *cmdb.ContinuousIntegrationInfo, s conversion.Scope) error {
	return autoConvert_v1_ContinuousIntegrationInfo_To_cmdb_ContinuousIntegrationInfo(in, out, s)
}

func autoConvert_cmdb_ContinuousIntegrationInfo_To_v1_ContinuousIntegrationInfo(in *cmdb.ContinuousIntegrationInfo, out *ContinuousIntegrationInfo, s conversion.Scope) error {
	out.ConfigPath = in.ConfigPath
	out.BuildImage = in.BuildImage
	out.FromImage = in.FromImage
	out.BuildDir = in.BuildDir
	out.BuildCommand = in.BuildCommand
	out.ArtifactPath = in.ArtifactPath
	out.PushRepository = in.PushRepository
	return nil
}

// Convert_cmdb_ContinuousIntegrationInfo_To_v1_ContinuousIntegrationInfo is an autogenerated conversion function.
func Convert_cmdb_ContinuousIntegrationInfo_To_v1_ContinuousIntegrationInfo(in *cmdb.ContinuousIntegrationInfo, out *ContinuousIntegrationInfo, s conversion.Scope) error {
	return autoConvert_cmdb_ContinuousIntegrationInfo_To_v1_ContinuousIntegrationInfo(in, out, s)
}

func autoConvert_v1_DockerRepository_To_cmdb_DockerRepository(in *DockerRepository, out *cmdb.DockerRepository, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_DockerRepositorySpec_To_cmdb_DockerRepositorySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_DockerRepositoryStatus_To_cmdb_DockerRepositoryStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_DockerRepository_To_cmdb_DockerRepository is an autogenerated conversion function.
func Convert_v1_DockerRepository_To_cmdb_DockerRepository(in *DockerRepository, out *cmdb.DockerRepository, s conversion.Scope) error {
	return autoConvert_v1_DockerRepository_To_cmdb_DockerRepository(in, out, s)
}

func autoConvert_cmdb_DockerRepository_To_v1_DockerRepository(in *cmdb.DockerRepository, out *DockerRepository, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_cmdb_DockerRepositorySpec_To_v1_DockerRepositorySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_cmdb_DockerRepositoryStatus_To_v1_DockerRepositoryStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_cmdb_DockerRepository_To_v1_DockerRepository is an autogenerated conversion function.
func Convert_cmdb_DockerRepository_To_v1_DockerRepository(in *cmdb.DockerRepository, out *DockerRepository, s conversion.Scope) error {
	return autoConvert_cmdb_DockerRepository_To_v1_DockerRepository(in, out, s)
}

func autoConvert_v1_DockerRepositoryList_To_cmdb_DockerRepositoryList(in *DockerRepositoryList, out *cmdb.DockerRepositoryList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]cmdb.DockerRepository)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_DockerRepositoryList_To_cmdb_DockerRepositoryList is an autogenerated conversion function.
func Convert_v1_DockerRepositoryList_To_cmdb_DockerRepositoryList(in *DockerRepositoryList, out *cmdb.DockerRepositoryList, s conversion.Scope) error {
	return autoConvert_v1_DockerRepositoryList_To_cmdb_DockerRepositoryList(in, out, s)
}

func autoConvert_cmdb_DockerRepositoryList_To_v1_DockerRepositoryList(in *cmdb.DockerRepositoryList, out *DockerRepositoryList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]DockerRepository)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_cmdb_DockerRepositoryList_To_v1_DockerRepositoryList is an autogenerated conversion function.
func Convert_cmdb_DockerRepositoryList_To_v1_DockerRepositoryList(in *cmdb.DockerRepositoryList, out *DockerRepositoryList, s conversion.Scope) error {
	return autoConvert_cmdb_DockerRepositoryList_To_v1_DockerRepositoryList(in, out, s)
}

func autoConvert_v1_DockerRepositorySpec_To_cmdb_DockerRepositorySpec(in *DockerRepositorySpec, out *cmdb.DockerRepositorySpec, s conversion.Scope) error {
	out.Registry = in.Registry
	out.User = in.User
	out.Password = in.Password
	return nil
}

// Convert_v1_DockerRepositorySpec_To_cmdb_DockerRepositorySpec is an autogenerated conversion function.
func Convert_v1_DockerRepositorySpec_To_cmdb_DockerRepositorySpec(in *DockerRepositorySpec, out *cmdb.DockerRepositorySpec, s conversion.Scope) error {
	return autoConvert_v1_DockerRepositorySpec_To_cmdb_DockerRepositorySpec(in, out, s)
}

func autoConvert_cmdb_DockerRepositorySpec_To_v1_DockerRepositorySpec(in *cmdb.DockerRepositorySpec, out *DockerRepositorySpec, s conversion.Scope) error {
	out.Registry = in.Registry
	out.User = in.User
	out.Password = in.Password
	return nil
}

// Convert_cmdb_DockerRepositorySpec_To_v1_DockerRepositorySpec is an autogenerated conversion function.
func Convert_cmdb_DockerRepositorySpec_To_v1_DockerRepositorySpec(in *cmdb.DockerRepositorySpec, out *DockerRepositorySpec, s conversion.Scope) error {
	return autoConvert_cmdb_DockerRepositorySpec_To_v1_DockerRepositorySpec(in, out, s)
}

func autoConvert_v1_DockerRepositoryStatus_To_cmdb_DockerRepositoryStatus(in *DockerRepositoryStatus, out *cmdb.DockerRepositoryStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1_DockerRepositoryStatus_To_cmdb_DockerRepositoryStatus is an autogenerated conversion function.
func Convert_v1_DockerRepositoryStatus_To_cmdb_DockerRepositoryStatus(in *DockerRepositoryStatus, out *cmdb.DockerRepositoryStatus, s conversion.Scope) error {
	return autoConvert_v1_DockerRepositoryStatus_To_cmdb_DockerRepositoryStatus(in, out, s)
}

func autoConvert_cmdb_DockerRepositoryStatus_To_v1_DockerRepositoryStatus(in *cmdb.DockerRepositoryStatus, out *DockerRepositoryStatus, s conversion.Scope) error {
	return nil
}

// Convert_cmdb_DockerRepositoryStatus_To_v1_DockerRepositoryStatus is an autogenerated conversion function.
func Convert_cmdb_DockerRepositoryStatus_To_v1_DockerRepositoryStatus(in *cmdb.DockerRepositoryStatus, out *DockerRepositoryStatus, s conversion.Scope) error {
	return autoConvert_cmdb_DockerRepositoryStatus_To_v1_DockerRepositoryStatus(in, out, s)
}

func autoConvert_v1_EnvInfo_To_cmdb_EnvInfo(in *EnvInfo, out *cmdb.EnvInfo, s conversion.Scope) error {
	out.Approval = in.Approval
	if err := Convert_v1_KubernetesInfo_To_cmdb_KubernetesInfo(&in.KubernetesInfo, &out.KubernetesInfo, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_EnvInfo_To_cmdb_EnvInfo is an autogenerated conversion function.
func Convert_v1_EnvInfo_To_cmdb_EnvInfo(in *EnvInfo, out *cmdb.EnvInfo, s conversion.Scope) error {
	return autoConvert_v1_EnvInfo_To_cmdb_EnvInfo(in, out, s)
}

func autoConvert_cmdb_EnvInfo_To_v1_EnvInfo(in *cmdb.EnvInfo, out *EnvInfo, s conversion.Scope) error {
	out.Approval = in.Approval
	if err := Convert_cmdb_KubernetesInfo_To_v1_KubernetesInfo(&in.KubernetesInfo, &out.KubernetesInfo, s); err != nil {
		return err
	}
	return nil
}

// Convert_cmdb_EnvInfo_To_v1_EnvInfo is an autogenerated conversion function.
func Convert_cmdb_EnvInfo_To_v1_EnvInfo(in *cmdb.EnvInfo, out *EnvInfo, s conversion.Scope) error {
	return autoConvert_cmdb_EnvInfo_To_v1_EnvInfo(in, out, s)
}

func autoConvert_v1_FeiShuApp_To_cmdb_FeiShuApp(in *FeiShuApp, out *cmdb.FeiShuApp, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_FeiShuAppSpec_To_cmdb_FeiShuAppSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_FeiShuAppStatus_To_cmdb_FeiShuAppStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_FeiShuApp_To_cmdb_FeiShuApp is an autogenerated conversion function.
func Convert_v1_FeiShuApp_To_cmdb_FeiShuApp(in *FeiShuApp, out *cmdb.FeiShuApp, s conversion.Scope) error {
	return autoConvert_v1_FeiShuApp_To_cmdb_FeiShuApp(in, out, s)
}

func autoConvert_cmdb_FeiShuApp_To_v1_FeiShuApp(in *cmdb.FeiShuApp, out *FeiShuApp, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_cmdb_FeiShuAppSpec_To_v1_FeiShuAppSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_cmdb_FeiShuAppStatus_To_v1_FeiShuAppStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_cmdb_FeiShuApp_To_v1_FeiShuApp is an autogenerated conversion function.
func Convert_cmdb_FeiShuApp_To_v1_FeiShuApp(in *cmdb.FeiShuApp, out *FeiShuApp, s conversion.Scope) error {
	return autoConvert_cmdb_FeiShuApp_To_v1_FeiShuApp(in, out, s)
}

func autoConvert_v1_FeiShuAppList_To_cmdb_FeiShuAppList(in *FeiShuAppList, out *cmdb.FeiShuAppList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]cmdb.FeiShuApp)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_FeiShuAppList_To_cmdb_FeiShuAppList is an autogenerated conversion function.
func Convert_v1_FeiShuAppList_To_cmdb_FeiShuAppList(in *FeiShuAppList, out *cmdb.FeiShuAppList, s conversion.Scope) error {
	return autoConvert_v1_FeiShuAppList_To_cmdb_FeiShuAppList(in, out, s)
}

func autoConvert_cmdb_FeiShuAppList_To_v1_FeiShuAppList(in *cmdb.FeiShuAppList, out *FeiShuAppList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]FeiShuApp)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_cmdb_FeiShuAppList_To_v1_FeiShuAppList is an autogenerated conversion function.
func Convert_cmdb_FeiShuAppList_To_v1_FeiShuAppList(in *cmdb.FeiShuAppList, out *FeiShuAppList, s conversion.Scope) error {
	return autoConvert_cmdb_FeiShuAppList_To_v1_FeiShuAppList(in, out, s)
}

func autoConvert_v1_FeiShuAppSpec_To_cmdb_FeiShuAppSpec(in *FeiShuAppSpec, out *cmdb.FeiShuAppSpec, s conversion.Scope) error {
	out.ID = in.ID
	out.Secret = in.Secret
	out.ApprovalCode = in.ApprovalCode
	return nil
}

// Convert_v1_FeiShuAppSpec_To_cmdb_FeiShuAppSpec is an autogenerated conversion function.
func Convert_v1_FeiShuAppSpec_To_cmdb_FeiShuAppSpec(in *FeiShuAppSpec, out *cmdb.FeiShuAppSpec, s conversion.Scope) error {
	return autoConvert_v1_FeiShuAppSpec_To_cmdb_FeiShuAppSpec(in, out, s)
}

func autoConvert_cmdb_FeiShuAppSpec_To_v1_FeiShuAppSpec(in *cmdb.FeiShuAppSpec, out *FeiShuAppSpec, s conversion.Scope) error {
	out.ID = in.ID
	out.Secret = in.Secret
	out.ApprovalCode = in.ApprovalCode
	return nil
}

// Convert_cmdb_FeiShuAppSpec_To_v1_FeiShuAppSpec is an autogenerated conversion function.
func Convert_cmdb_FeiShuAppSpec_To_v1_FeiShuAppSpec(in *cmdb.FeiShuAppSpec, out *FeiShuAppSpec, s conversion.Scope) error {
	return autoConvert_cmdb_FeiShuAppSpec_To_v1_FeiShuAppSpec(in, out, s)
}

func autoConvert_v1_FeiShuAppStatus_To_cmdb_FeiShuAppStatus(in *FeiShuAppStatus, out *cmdb.FeiShuAppStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1_FeiShuAppStatus_To_cmdb_FeiShuAppStatus is an autogenerated conversion function.
func Convert_v1_FeiShuAppStatus_To_cmdb_FeiShuAppStatus(in *FeiShuAppStatus, out *cmdb.FeiShuAppStatus, s conversion.Scope) error {
	return autoConvert_v1_FeiShuAppStatus_To_cmdb_FeiShuAppStatus(in, out, s)
}

func autoConvert_cmdb_FeiShuAppStatus_To_v1_FeiShuAppStatus(in *cmdb.FeiShuAppStatus, out *FeiShuAppStatus, s conversion.Scope) error {
	return nil
}

// Convert_cmdb_FeiShuAppStatus_To_v1_FeiShuAppStatus is an autogenerated conversion function.
func Convert_cmdb_FeiShuAppStatus_To_v1_FeiShuAppStatus(in *cmdb.FeiShuAppStatus, out *FeiShuAppStatus, s conversion.Scope) error {
	return autoConvert_cmdb_FeiShuAppStatus_To_v1_FeiShuAppStatus(in, out, s)
}

func autoConvert_v1_Gitlab_To_cmdb_Gitlab(in *Gitlab, out *cmdb.Gitlab, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_GitlabSpec_To_cmdb_GitlabSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_GitlabStatus_To_cmdb_GitlabStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_Gitlab_To_cmdb_Gitlab is an autogenerated conversion function.
func Convert_v1_Gitlab_To_cmdb_Gitlab(in *Gitlab, out *cmdb.Gitlab, s conversion.Scope) error {
	return autoConvert_v1_Gitlab_To_cmdb_Gitlab(in, out, s)
}

func autoConvert_cmdb_Gitlab_To_v1_Gitlab(in *cmdb.Gitlab, out *Gitlab, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_cmdb_GitlabSpec_To_v1_GitlabSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_cmdb_GitlabStatus_To_v1_GitlabStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_cmdb_Gitlab_To_v1_Gitlab is an autogenerated conversion function.
func Convert_cmdb_Gitlab_To_v1_Gitlab(in *cmdb.Gitlab, out *Gitlab, s conversion.Scope) error {
	return autoConvert_cmdb_Gitlab_To_v1_Gitlab(in, out, s)
}

func autoConvert_v1_GitlabInfo_To_cmdb_GitlabInfo(in *GitlabInfo, out *cmdb.GitlabInfo, s conversion.Scope) error {
	out.Name = in.Name
	out.ProjectID = in.ProjectID
	return nil
}

// Convert_v1_GitlabInfo_To_cmdb_GitlabInfo is an autogenerated conversion function.
func Convert_v1_GitlabInfo_To_cmdb_GitlabInfo(in *GitlabInfo, out *cmdb.GitlabInfo, s conversion.Scope) error {
	return autoConvert_v1_GitlabInfo_To_cmdb_GitlabInfo(in, out, s)
}

func autoConvert_cmdb_GitlabInfo_To_v1_GitlabInfo(in *cmdb.GitlabInfo, out *GitlabInfo, s conversion.Scope) error {
	out.Name = in.Name
	out.ProjectID = in.ProjectID
	return nil
}

// Convert_cmdb_GitlabInfo_To_v1_GitlabInfo is an autogenerated conversion function.
func Convert_cmdb_GitlabInfo_To_v1_GitlabInfo(in *cmdb.GitlabInfo, out *GitlabInfo, s conversion.Scope) error {
	return autoConvert_cmdb_GitlabInfo_To_v1_GitlabInfo(in, out, s)
}

func autoConvert_v1_GitlabList_To_cmdb_GitlabList(in *GitlabList, out *cmdb.GitlabList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]cmdb.Gitlab)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_GitlabList_To_cmdb_GitlabList is an autogenerated conversion function.
func Convert_v1_GitlabList_To_cmdb_GitlabList(in *GitlabList, out *cmdb.GitlabList, s conversion.Scope) error {
	return autoConvert_v1_GitlabList_To_cmdb_GitlabList(in, out, s)
}

func autoConvert_cmdb_GitlabList_To_v1_GitlabList(in *cmdb.GitlabList, out *GitlabList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Gitlab)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_cmdb_GitlabList_To_v1_GitlabList is an autogenerated conversion function.
func Convert_cmdb_GitlabList_To_v1_GitlabList(in *cmdb.GitlabList, out *GitlabList, s conversion.Scope) error {
	return autoConvert_cmdb_GitlabList_To_v1_GitlabList(in, out, s)
}

func autoConvert_v1_GitlabSpec_To_cmdb_GitlabSpec(in *GitlabSpec, out *cmdb.GitlabSpec, s conversion.Scope) error {
	out.URL = in.URL
	out.Token = in.Token
	out.ProjectIndex = *(*map[cmdb.ProjectStringID]cmdb.Project)(unsafe.Pointer(&in.ProjectIndex))
	return nil
}

// Convert_v1_GitlabSpec_To_cmdb_GitlabSpec is an autogenerated conversion function.
func Convert_v1_GitlabSpec_To_cmdb_GitlabSpec(in *GitlabSpec, out *cmdb.GitlabSpec, s conversion.Scope) error {
	return autoConvert_v1_GitlabSpec_To_cmdb_GitlabSpec(in, out, s)
}

func autoConvert_cmdb_GitlabSpec_To_v1_GitlabSpec(in *cmdb.GitlabSpec, out *GitlabSpec, s conversion.Scope) error {
	out.URL = in.URL
	out.Token = in.Token
	out.ProjectIndex = *(*map[ProjectStringID]Project)(unsafe.Pointer(&in.ProjectIndex))
	return nil
}

// Convert_cmdb_GitlabSpec_To_v1_GitlabSpec is an autogenerated conversion function.
func Convert_cmdb_GitlabSpec_To_v1_GitlabSpec(in *cmdb.GitlabSpec, out *GitlabSpec, s conversion.Scope) error {
	return autoConvert_cmdb_GitlabSpec_To_v1_GitlabSpec(in, out, s)
}

func autoConvert_v1_GitlabStatus_To_cmdb_GitlabStatus(in *GitlabStatus, out *cmdb.GitlabStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1_GitlabStatus_To_cmdb_GitlabStatus is an autogenerated conversion function.
func Convert_v1_GitlabStatus_To_cmdb_GitlabStatus(in *GitlabStatus, out *cmdb.GitlabStatus, s conversion.Scope) error {
	return autoConvert_v1_GitlabStatus_To_cmdb_GitlabStatus(in, out, s)
}

func autoConvert_cmdb_GitlabStatus_To_v1_GitlabStatus(in *cmdb.GitlabStatus, out *GitlabStatus, s conversion.Scope) error {
	return nil
}

// Convert_cmdb_GitlabStatus_To_v1_GitlabStatus is an autogenerated conversion function.
func Convert_cmdb_GitlabStatus_To_v1_GitlabStatus(in *cmdb.GitlabStatus, out *GitlabStatus, s conversion.Scope) error {
	return autoConvert_cmdb_GitlabStatus_To_v1_GitlabStatus(in, out, s)
}

func autoConvert_v1_Kubernetes_To_cmdb_Kubernetes(in *Kubernetes, out *cmdb.Kubernetes, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_KubernetesSpec_To_cmdb_KubernetesSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_KubernetesStatus_To_cmdb_KubernetesStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_Kubernetes_To_cmdb_Kubernetes is an autogenerated conversion function.
func Convert_v1_Kubernetes_To_cmdb_Kubernetes(in *Kubernetes, out *cmdb.Kubernetes, s conversion.Scope) error {
	return autoConvert_v1_Kubernetes_To_cmdb_Kubernetes(in, out, s)
}

func autoConvert_cmdb_Kubernetes_To_v1_Kubernetes(in *cmdb.Kubernetes, out *Kubernetes, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_cmdb_KubernetesSpec_To_v1_KubernetesSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_cmdb_KubernetesStatus_To_v1_KubernetesStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_cmdb_Kubernetes_To_v1_Kubernetes is an autogenerated conversion function.
func Convert_cmdb_Kubernetes_To_v1_Kubernetes(in *cmdb.Kubernetes, out *Kubernetes, s conversion.Scope) error {
	return autoConvert_cmdb_Kubernetes_To_v1_Kubernetes(in, out, s)
}

func autoConvert_v1_KubernetesInfo_To_cmdb_KubernetesInfo(in *KubernetesInfo, out *cmdb.KubernetesInfo, s conversion.Scope) error {
	out.Name = in.Name
	out.Namespace = in.Namespace
	return nil
}

// Convert_v1_KubernetesInfo_To_cmdb_KubernetesInfo is an autogenerated conversion function.
func Convert_v1_KubernetesInfo_To_cmdb_KubernetesInfo(in *KubernetesInfo, out *cmdb.KubernetesInfo, s conversion.Scope) error {
	return autoConvert_v1_KubernetesInfo_To_cmdb_KubernetesInfo(in, out, s)
}

func autoConvert_cmdb_KubernetesInfo_To_v1_KubernetesInfo(in *cmdb.KubernetesInfo, out *KubernetesInfo, s conversion.Scope) error {
	out.Name = in.Name
	out.Namespace = in.Namespace
	return nil
}

// Convert_cmdb_KubernetesInfo_To_v1_KubernetesInfo is an autogenerated conversion function.
func Convert_cmdb_KubernetesInfo_To_v1_KubernetesInfo(in *cmdb.KubernetesInfo, out *KubernetesInfo, s conversion.Scope) error {
	return autoConvert_cmdb_KubernetesInfo_To_v1_KubernetesInfo(in, out, s)
}

func autoConvert_v1_KubernetesList_To_cmdb_KubernetesList(in *KubernetesList, out *cmdb.KubernetesList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]cmdb.Kubernetes)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_KubernetesList_To_cmdb_KubernetesList is an autogenerated conversion function.
func Convert_v1_KubernetesList_To_cmdb_KubernetesList(in *KubernetesList, out *cmdb.KubernetesList, s conversion.Scope) error {
	return autoConvert_v1_KubernetesList_To_cmdb_KubernetesList(in, out, s)
}

func autoConvert_cmdb_KubernetesList_To_v1_KubernetesList(in *cmdb.KubernetesList, out *KubernetesList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Kubernetes)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_cmdb_KubernetesList_To_v1_KubernetesList is an autogenerated conversion function.
func Convert_cmdb_KubernetesList_To_v1_KubernetesList(in *cmdb.KubernetesList, out *KubernetesList, s conversion.Scope) error {
	return autoConvert_cmdb_KubernetesList_To_v1_KubernetesList(in, out, s)
}

func autoConvert_v1_KubernetesSpec_To_cmdb_KubernetesSpec(in *KubernetesSpec, out *cmdb.KubernetesSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.Config = in.Config
	return nil
}

// Convert_v1_KubernetesSpec_To_cmdb_KubernetesSpec is an autogenerated conversion function.
func Convert_v1_KubernetesSpec_To_cmdb_KubernetesSpec(in *KubernetesSpec, out *cmdb.KubernetesSpec, s conversion.Scope) error {
	return autoConvert_v1_KubernetesSpec_To_cmdb_KubernetesSpec(in, out, s)
}

func autoConvert_cmdb_KubernetesSpec_To_v1_KubernetesSpec(in *cmdb.KubernetesSpec, out *KubernetesSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.Config = in.Config
	return nil
}

// Convert_cmdb_KubernetesSpec_To_v1_KubernetesSpec is an autogenerated conversion function.
func Convert_cmdb_KubernetesSpec_To_v1_KubernetesSpec(in *cmdb.KubernetesSpec, out *KubernetesSpec, s conversion.Scope) error {
	return autoConvert_cmdb_KubernetesSpec_To_v1_KubernetesSpec(in, out, s)
}

func autoConvert_v1_KubernetesStatus_To_cmdb_KubernetesStatus(in *KubernetesStatus, out *cmdb.KubernetesStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1_KubernetesStatus_To_cmdb_KubernetesStatus is an autogenerated conversion function.
func Convert_v1_KubernetesStatus_To_cmdb_KubernetesStatus(in *KubernetesStatus, out *cmdb.KubernetesStatus, s conversion.Scope) error {
	return autoConvert_v1_KubernetesStatus_To_cmdb_KubernetesStatus(in, out, s)
}

func autoConvert_cmdb_KubernetesStatus_To_v1_KubernetesStatus(in *cmdb.KubernetesStatus, out *KubernetesStatus, s conversion.Scope) error {
	return nil
}

// Convert_cmdb_KubernetesStatus_To_v1_KubernetesStatus is an autogenerated conversion function.
func Convert_cmdb_KubernetesStatus_To_v1_KubernetesStatus(in *cmdb.KubernetesStatus, out *KubernetesStatus, s conversion.Scope) error {
	return autoConvert_cmdb_KubernetesStatus_To_v1_KubernetesStatus(in, out, s)
}

func autoConvert_v1_Product_To_cmdb_Product(in *Product, out *cmdb.Product, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_ProductSpec_To_cmdb_ProductSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_ProductStatus_To_cmdb_ProductStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_Product_To_cmdb_Product is an autogenerated conversion function.
func Convert_v1_Product_To_cmdb_Product(in *Product, out *cmdb.Product, s conversion.Scope) error {
	return autoConvert_v1_Product_To_cmdb_Product(in, out, s)
}

func autoConvert_cmdb_Product_To_v1_Product(in *cmdb.Product, out *Product, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_cmdb_ProductSpec_To_v1_ProductSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_cmdb_ProductStatus_To_v1_ProductStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_cmdb_Product_To_v1_Product is an autogenerated conversion function.
func Convert_cmdb_Product_To_v1_Product(in *cmdb.Product, out *Product, s conversion.Scope) error {
	return autoConvert_cmdb_Product_To_v1_Product(in, out, s)
}

func autoConvert_v1_ProductList_To_cmdb_ProductList(in *ProductList, out *cmdb.ProductList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]cmdb.Product)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_ProductList_To_cmdb_ProductList is an autogenerated conversion function.
func Convert_v1_ProductList_To_cmdb_ProductList(in *ProductList, out *cmdb.ProductList, s conversion.Scope) error {
	return autoConvert_v1_ProductList_To_cmdb_ProductList(in, out, s)
}

func autoConvert_cmdb_ProductList_To_v1_ProductList(in *cmdb.ProductList, out *ProductList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Product)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_cmdb_ProductList_To_v1_ProductList is an autogenerated conversion function.
func Convert_cmdb_ProductList_To_v1_ProductList(in *cmdb.ProductList, out *ProductList, s conversion.Scope) error {
	return autoConvert_cmdb_ProductList_To_v1_ProductList(in, out, s)
}

func autoConvert_v1_ProductSpec_To_cmdb_ProductSpec(in *ProductSpec, out *cmdb.ProductSpec, s conversion.Scope) error {
	return nil
}

// Convert_v1_ProductSpec_To_cmdb_ProductSpec is an autogenerated conversion function.
func Convert_v1_ProductSpec_To_cmdb_ProductSpec(in *ProductSpec, out *cmdb.ProductSpec, s conversion.Scope) error {
	return autoConvert_v1_ProductSpec_To_cmdb_ProductSpec(in, out, s)
}

func autoConvert_cmdb_ProductSpec_To_v1_ProductSpec(in *cmdb.ProductSpec, out *ProductSpec, s conversion.Scope) error {
	return nil
}

// Convert_cmdb_ProductSpec_To_v1_ProductSpec is an autogenerated conversion function.
func Convert_cmdb_ProductSpec_To_v1_ProductSpec(in *cmdb.ProductSpec, out *ProductSpec, s conversion.Scope) error {
	return autoConvert_cmdb_ProductSpec_To_v1_ProductSpec(in, out, s)
}

func autoConvert_v1_ProductStatus_To_cmdb_ProductStatus(in *ProductStatus, out *cmdb.ProductStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1_ProductStatus_To_cmdb_ProductStatus is an autogenerated conversion function.
func Convert_v1_ProductStatus_To_cmdb_ProductStatus(in *ProductStatus, out *cmdb.ProductStatus, s conversion.Scope) error {
	return autoConvert_v1_ProductStatus_To_cmdb_ProductStatus(in, out, s)
}

func autoConvert_cmdb_ProductStatus_To_v1_ProductStatus(in *cmdb.ProductStatus, out *ProductStatus, s conversion.Scope) error {
	return nil
}

// Convert_cmdb_ProductStatus_To_v1_ProductStatus is an autogenerated conversion function.
func Convert_cmdb_ProductStatus_To_v1_ProductStatus(in *cmdb.ProductStatus, out *ProductStatus, s conversion.Scope) error {
	return autoConvert_cmdb_ProductStatus_To_v1_ProductStatus(in, out, s)
}

func autoConvert_v1_Project_To_cmdb_Project(in *Project, out *cmdb.Project, s conversion.Scope) error {
	out.ServersMap = *(*map[cmdb.ServerName]cmdb.ServerProduct)(unsafe.Pointer(&in.ServersMap))
	out.HooksMap = *(*map[cmdb.GitlabWebhookEventType]int)(unsafe.Pointer(&in.HooksMap))
	return nil
}

// Convert_v1_Project_To_cmdb_Project is an autogenerated conversion function.
func Convert_v1_Project_To_cmdb_Project(in *Project, out *cmdb.Project, s conversion.Scope) error {
	return autoConvert_v1_Project_To_cmdb_Project(in, out, s)
}

func autoConvert_cmdb_Project_To_v1_Project(in *cmdb.Project, out *Project, s conversion.Scope) error {
	out.ServersMap = *(*map[ServerName]ServerProduct)(unsafe.Pointer(&in.ServersMap))
	out.HooksMap = *(*map[GitlabWebhookEventType]int)(unsafe.Pointer(&in.HooksMap))
	return nil
}

// Convert_cmdb_Project_To_v1_Project is an autogenerated conversion function.
func Convert_cmdb_Project_To_v1_Project(in *cmdb.Project, out *Project, s conversion.Scope) error {
	return autoConvert_cmdb_Project_To_v1_Project(in, out, s)
}

func autoConvert_v1_Server_To_cmdb_Server(in *Server, out *cmdb.Server, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_ServerSpec_To_cmdb_ServerSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_ServerStatus_To_cmdb_ServerStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_Server_To_cmdb_Server is an autogenerated conversion function.
func Convert_v1_Server_To_cmdb_Server(in *Server, out *cmdb.Server, s conversion.Scope) error {
	return autoConvert_v1_Server_To_cmdb_Server(in, out, s)
}

func autoConvert_cmdb_Server_To_v1_Server(in *cmdb.Server, out *Server, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_cmdb_ServerSpec_To_v1_ServerSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_cmdb_ServerStatus_To_v1_ServerStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_cmdb_Server_To_v1_Server is an autogenerated conversion function.
func Convert_cmdb_Server_To_v1_Server(in *cmdb.Server, out *Server, s conversion.Scope) error {
	return autoConvert_cmdb_Server_To_v1_Server(in, out, s)
}

func autoConvert_v1_ServerList_To_cmdb_ServerList(in *ServerList, out *cmdb.ServerList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]cmdb.Server)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_ServerList_To_cmdb_ServerList is an autogenerated conversion function.
func Convert_v1_ServerList_To_cmdb_ServerList(in *ServerList, out *cmdb.ServerList, s conversion.Scope) error {
	return autoConvert_v1_ServerList_To_cmdb_ServerList(in, out, s)
}

func autoConvert_cmdb_ServerList_To_v1_ServerList(in *cmdb.ServerList, out *ServerList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Server)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_cmdb_ServerList_To_v1_ServerList is an autogenerated conversion function.
func Convert_cmdb_ServerList_To_v1_ServerList(in *cmdb.ServerList, out *ServerList, s conversion.Scope) error {
	return autoConvert_cmdb_ServerList_To_v1_ServerList(in, out, s)
}

func autoConvert_v1_ServerSpec_To_cmdb_ServerSpec(in *ServerSpec, out *cmdb.ServerSpec, s conversion.Scope) error {
	if err := Convert_v1_GitlabInfo_To_cmdb_GitlabInfo(&in.GitlabInfo, &out.GitlabInfo, s); err != nil {
		return err
	}
	if err := Convert_v1_ContinuousIntegrationInfo_To_cmdb_ContinuousIntegrationInfo(&in.ContinuousIntegrationInfo, &out.ContinuousIntegrationInfo, s); err != nil {
		return err
	}
	if err := Convert_v1_ContinuousDeploymentInfo_To_cmdb_ContinuousDeploymentInfo(&in.ContinuousDeploymentInfo, &out.ContinuousDeploymentInfo, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_ServerSpec_To_cmdb_ServerSpec is an autogenerated conversion function.
func Convert_v1_ServerSpec_To_cmdb_ServerSpec(in *ServerSpec, out *cmdb.ServerSpec, s conversion.Scope) error {
	return autoConvert_v1_ServerSpec_To_cmdb_ServerSpec(in, out, s)
}

func autoConvert_cmdb_ServerSpec_To_v1_ServerSpec(in *cmdb.ServerSpec, out *ServerSpec, s conversion.Scope) error {
	if err := Convert_cmdb_GitlabInfo_To_v1_GitlabInfo(&in.GitlabInfo, &out.GitlabInfo, s); err != nil {
		return err
	}
	if err := Convert_cmdb_ContinuousIntegrationInfo_To_v1_ContinuousIntegrationInfo(&in.ContinuousIntegrationInfo, &out.ContinuousIntegrationInfo, s); err != nil {
		return err
	}
	if err := Convert_cmdb_ContinuousDeploymentInfo_To_v1_ContinuousDeploymentInfo(&in.ContinuousDeploymentInfo, &out.ContinuousDeploymentInfo, s); err != nil {
		return err
	}
	return nil
}

// Convert_cmdb_ServerSpec_To_v1_ServerSpec is an autogenerated conversion function.
func Convert_cmdb_ServerSpec_To_v1_ServerSpec(in *cmdb.ServerSpec, out *ServerSpec, s conversion.Scope) error {
	return autoConvert_cmdb_ServerSpec_To_v1_ServerSpec(in, out, s)
}

func autoConvert_v1_ServerStatus_To_cmdb_ServerStatus(in *ServerStatus, out *cmdb.ServerStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1_ServerStatus_To_cmdb_ServerStatus is an autogenerated conversion function.
func Convert_v1_ServerStatus_To_cmdb_ServerStatus(in *ServerStatus, out *cmdb.ServerStatus, s conversion.Scope) error {
	return autoConvert_v1_ServerStatus_To_cmdb_ServerStatus(in, out, s)
}

func autoConvert_cmdb_ServerStatus_To_v1_ServerStatus(in *cmdb.ServerStatus, out *ServerStatus, s conversion.Scope) error {
	return nil
}

// Convert_cmdb_ServerStatus_To_v1_ServerStatus is an autogenerated conversion function.
func Convert_cmdb_ServerStatus_To_v1_ServerStatus(in *cmdb.ServerStatus, out *ServerStatus, s conversion.Scope) error {
	return autoConvert_cmdb_ServerStatus_To_v1_ServerStatus(in, out, s)
}
