//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1

import (
	unsafe "unsafe"

	app "github.com/solid-wang/covid/pkg/apis/app"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Application)(nil), (*app.Application)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Application_To_app_Application(a.(*Application), b.(*app.Application), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*app.Application)(nil), (*Application)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_app_Application_To_v1_Application(a.(*app.Application), b.(*Application), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ApplicationList)(nil), (*app.ApplicationList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ApplicationList_To_app_ApplicationList(a.(*ApplicationList), b.(*app.ApplicationList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*app.ApplicationList)(nil), (*ApplicationList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_app_ApplicationList_To_v1_ApplicationList(a.(*app.ApplicationList), b.(*ApplicationList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ApplicationSpec)(nil), (*app.ApplicationSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ApplicationSpec_To_app_ApplicationSpec(a.(*ApplicationSpec), b.(*app.ApplicationSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*app.ApplicationSpec)(nil), (*ApplicationSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_app_ApplicationSpec_To_v1_ApplicationSpec(a.(*app.ApplicationSpec), b.(*ApplicationSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ApplicationStatus)(nil), (*app.ApplicationStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ApplicationStatus_To_app_ApplicationStatus(a.(*ApplicationStatus), b.(*app.ApplicationStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*app.ApplicationStatus)(nil), (*ApplicationStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_app_ApplicationStatus_To_v1_ApplicationStatus(a.(*app.ApplicationStatus), b.(*ApplicationStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ContinuousDeploymentTemplate)(nil), (*app.ContinuousDeploymentTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ContinuousDeploymentTemplate_To_app_ContinuousDeploymentTemplate(a.(*ContinuousDeploymentTemplate), b.(*app.ContinuousDeploymentTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*app.ContinuousDeploymentTemplate)(nil), (*ContinuousDeploymentTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_app_ContinuousDeploymentTemplate_To_v1_ContinuousDeploymentTemplate(a.(*app.ContinuousDeploymentTemplate), b.(*ContinuousDeploymentTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ContinuousIntegrationTemplate)(nil), (*app.ContinuousIntegrationTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ContinuousIntegrationTemplate_To_app_ContinuousIntegrationTemplate(a.(*ContinuousIntegrationTemplate), b.(*app.ContinuousIntegrationTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*app.ContinuousIntegrationTemplate)(nil), (*ContinuousIntegrationTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_app_ContinuousIntegrationTemplate_To_v1_ContinuousIntegrationTemplate(a.(*app.ContinuousIntegrationTemplate), b.(*ContinuousIntegrationTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Env)(nil), (*app.Env)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Env_To_app_Env(a.(*Env), b.(*app.Env), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*app.Env)(nil), (*Env)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_app_Env_To_v1_Env(a.(*app.Env), b.(*Env), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Port)(nil), (*app.Port)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Port_To_app_Port(a.(*Port), b.(*app.Port), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*app.Port)(nil), (*Port)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_app_Port_To_v1_Port(a.(*app.Port), b.(*Port), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Product)(nil), (*app.Product)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Product_To_app_Product(a.(*Product), b.(*app.Product), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*app.Product)(nil), (*Product)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_app_Product_To_v1_Product(a.(*app.Product), b.(*Product), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProductList)(nil), (*app.ProductList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ProductList_To_app_ProductList(a.(*ProductList), b.(*app.ProductList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*app.ProductList)(nil), (*ProductList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_app_ProductList_To_v1_ProductList(a.(*app.ProductList), b.(*ProductList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProductSpec)(nil), (*app.ProductSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ProductSpec_To_app_ProductSpec(a.(*ProductSpec), b.(*app.ProductSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*app.ProductSpec)(nil), (*ProductSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_app_ProductSpec_To_v1_ProductSpec(a.(*app.ProductSpec), b.(*ProductSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProductStatus)(nil), (*app.ProductStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ProductStatus_To_app_ProductStatus(a.(*ProductStatus), b.(*app.ProductStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*app.ProductStatus)(nil), (*ProductStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_app_ProductStatus_To_v1_ProductStatus(a.(*app.ProductStatus), b.(*ProductStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Variable)(nil), (*app.Variable)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Variable_To_app_Variable(a.(*Variable), b.(*app.Variable), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*app.Variable)(nil), (*Variable)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_app_Variable_To_v1_Variable(a.(*app.Variable), b.(*Variable), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1_Application_To_app_Application(in *Application, out *app.Application, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_ApplicationSpec_To_app_ApplicationSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_ApplicationStatus_To_app_ApplicationStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_Application_To_app_Application is an autogenerated conversion function.
func Convert_v1_Application_To_app_Application(in *Application, out *app.Application, s conversion.Scope) error {
	return autoConvert_v1_Application_To_app_Application(in, out, s)
}

func autoConvert_app_Application_To_v1_Application(in *app.Application, out *Application, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_app_ApplicationSpec_To_v1_ApplicationSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_app_ApplicationStatus_To_v1_ApplicationStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_app_Application_To_v1_Application is an autogenerated conversion function.
func Convert_app_Application_To_v1_Application(in *app.Application, out *Application, s conversion.Scope) error {
	return autoConvert_app_Application_To_v1_Application(in, out, s)
}

func autoConvert_v1_ApplicationList_To_app_ApplicationList(in *ApplicationList, out *app.ApplicationList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]app.Application)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_ApplicationList_To_app_ApplicationList is an autogenerated conversion function.
func Convert_v1_ApplicationList_To_app_ApplicationList(in *ApplicationList, out *app.ApplicationList, s conversion.Scope) error {
	return autoConvert_v1_ApplicationList_To_app_ApplicationList(in, out, s)
}

func autoConvert_app_ApplicationList_To_v1_ApplicationList(in *app.ApplicationList, out *ApplicationList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Application)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_app_ApplicationList_To_v1_ApplicationList is an autogenerated conversion function.
func Convert_app_ApplicationList_To_v1_ApplicationList(in *app.ApplicationList, out *ApplicationList, s conversion.Scope) error {
	return autoConvert_app_ApplicationList_To_v1_ApplicationList(in, out, s)
}

func autoConvert_v1_ApplicationSpec_To_app_ApplicationSpec(in *ApplicationSpec, out *app.ApplicationSpec, s conversion.Scope) error {
	out.GitlabName = in.GitlabName
	out.ProjectID = in.ProjectID
	out.DockerRepositoryName = in.DockerRepositoryName
	out.BranchEnvMap = *(*map[string]string)(unsafe.Pointer(&in.BranchEnvMap))
	if err := Convert_v1_ContinuousIntegrationTemplate_To_app_ContinuousIntegrationTemplate(&in.ContinuousIntegrationTemplate, &out.ContinuousIntegrationTemplate, s); err != nil {
		return err
	}
	if err := Convert_v1_ContinuousDeploymentTemplate_To_app_ContinuousDeploymentTemplate(&in.ContinuousDeploymentTemplate, &out.ContinuousDeploymentTemplate, s); err != nil {
		return err
	}
	out.Owner = in.Owner
	return nil
}

// Convert_v1_ApplicationSpec_To_app_ApplicationSpec is an autogenerated conversion function.
func Convert_v1_ApplicationSpec_To_app_ApplicationSpec(in *ApplicationSpec, out *app.ApplicationSpec, s conversion.Scope) error {
	return autoConvert_v1_ApplicationSpec_To_app_ApplicationSpec(in, out, s)
}

func autoConvert_app_ApplicationSpec_To_v1_ApplicationSpec(in *app.ApplicationSpec, out *ApplicationSpec, s conversion.Scope) error {
	out.GitlabName = in.GitlabName
	out.ProjectID = in.ProjectID
	out.DockerRepositoryName = in.DockerRepositoryName
	out.BranchEnvMap = *(*map[string]string)(unsafe.Pointer(&in.BranchEnvMap))
	if err := Convert_app_ContinuousIntegrationTemplate_To_v1_ContinuousIntegrationTemplate(&in.ContinuousIntegrationTemplate, &out.ContinuousIntegrationTemplate, s); err != nil {
		return err
	}
	if err := Convert_app_ContinuousDeploymentTemplate_To_v1_ContinuousDeploymentTemplate(&in.ContinuousDeploymentTemplate, &out.ContinuousDeploymentTemplate, s); err != nil {
		return err
	}
	out.Owner = in.Owner
	return nil
}

// Convert_app_ApplicationSpec_To_v1_ApplicationSpec is an autogenerated conversion function.
func Convert_app_ApplicationSpec_To_v1_ApplicationSpec(in *app.ApplicationSpec, out *ApplicationSpec, s conversion.Scope) error {
	return autoConvert_app_ApplicationSpec_To_v1_ApplicationSpec(in, out, s)
}

func autoConvert_v1_ApplicationStatus_To_app_ApplicationStatus(in *ApplicationStatus, out *app.ApplicationStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1_ApplicationStatus_To_app_ApplicationStatus is an autogenerated conversion function.
func Convert_v1_ApplicationStatus_To_app_ApplicationStatus(in *ApplicationStatus, out *app.ApplicationStatus, s conversion.Scope) error {
	return autoConvert_v1_ApplicationStatus_To_app_ApplicationStatus(in, out, s)
}

func autoConvert_app_ApplicationStatus_To_v1_ApplicationStatus(in *app.ApplicationStatus, out *ApplicationStatus, s conversion.Scope) error {
	return nil
}

// Convert_app_ApplicationStatus_To_v1_ApplicationStatus is an autogenerated conversion function.
func Convert_app_ApplicationStatus_To_v1_ApplicationStatus(in *app.ApplicationStatus, out *ApplicationStatus, s conversion.Scope) error {
	return autoConvert_app_ApplicationStatus_To_v1_ApplicationStatus(in, out, s)
}

func autoConvert_v1_ContinuousDeploymentTemplate_To_app_ContinuousDeploymentTemplate(in *ContinuousDeploymentTemplate, out *app.ContinuousDeploymentTemplate, s conversion.Scope) error {
	out.Command = *(*[]string)(unsafe.Pointer(&in.Command))
	out.Ports = *(*[]app.Port)(unsafe.Pointer(&in.Ports))
	out.EnvMap = *(*map[string]*app.Env)(unsafe.Pointer(&in.EnvMap))
	return nil
}

// Convert_v1_ContinuousDeploymentTemplate_To_app_ContinuousDeploymentTemplate is an autogenerated conversion function.
func Convert_v1_ContinuousDeploymentTemplate_To_app_ContinuousDeploymentTemplate(in *ContinuousDeploymentTemplate, out *app.ContinuousDeploymentTemplate, s conversion.Scope) error {
	return autoConvert_v1_ContinuousDeploymentTemplate_To_app_ContinuousDeploymentTemplate(in, out, s)
}

func autoConvert_app_ContinuousDeploymentTemplate_To_v1_ContinuousDeploymentTemplate(in *app.ContinuousDeploymentTemplate, out *ContinuousDeploymentTemplate, s conversion.Scope) error {
	out.Command = *(*[]string)(unsafe.Pointer(&in.Command))
	out.Ports = *(*[]Port)(unsafe.Pointer(&in.Ports))
	out.EnvMap = *(*map[string]*Env)(unsafe.Pointer(&in.EnvMap))
	return nil
}

// Convert_app_ContinuousDeploymentTemplate_To_v1_ContinuousDeploymentTemplate is an autogenerated conversion function.
func Convert_app_ContinuousDeploymentTemplate_To_v1_ContinuousDeploymentTemplate(in *app.ContinuousDeploymentTemplate, out *ContinuousDeploymentTemplate, s conversion.Scope) error {
	return autoConvert_app_ContinuousDeploymentTemplate_To_v1_ContinuousDeploymentTemplate(in, out, s)
}

func autoConvert_v1_ContinuousIntegrationTemplate_To_app_ContinuousIntegrationTemplate(in *ContinuousIntegrationTemplate, out *app.ContinuousIntegrationTemplate, s conversion.Scope) error {
	out.ConfigPath = in.ConfigPath
	out.BuildImage = in.BuildImage
	out.FromImage = in.FromImage
	out.BuildDir = in.BuildDir
	out.BuildCommand = in.BuildCommand
	out.ArtifactPath = in.ArtifactPath
	return nil
}

// Convert_v1_ContinuousIntegrationTemplate_To_app_ContinuousIntegrationTemplate is an autogenerated conversion function.
func Convert_v1_ContinuousIntegrationTemplate_To_app_ContinuousIntegrationTemplate(in *ContinuousIntegrationTemplate, out *app.ContinuousIntegrationTemplate, s conversion.Scope) error {
	return autoConvert_v1_ContinuousIntegrationTemplate_To_app_ContinuousIntegrationTemplate(in, out, s)
}

func autoConvert_app_ContinuousIntegrationTemplate_To_v1_ContinuousIntegrationTemplate(in *app.ContinuousIntegrationTemplate, out *ContinuousIntegrationTemplate, s conversion.Scope) error {
	out.ConfigPath = in.ConfigPath
	out.BuildImage = in.BuildImage
	out.FromImage = in.FromImage
	out.BuildDir = in.BuildDir
	out.BuildCommand = in.BuildCommand
	out.ArtifactPath = in.ArtifactPath
	return nil
}

// Convert_app_ContinuousIntegrationTemplate_To_v1_ContinuousIntegrationTemplate is an autogenerated conversion function.
func Convert_app_ContinuousIntegrationTemplate_To_v1_ContinuousIntegrationTemplate(in *app.ContinuousIntegrationTemplate, out *ContinuousIntegrationTemplate, s conversion.Scope) error {
	return autoConvert_app_ContinuousIntegrationTemplate_To_v1_ContinuousIntegrationTemplate(in, out, s)
}

func autoConvert_v1_Env_To_app_Env(in *Env, out *app.Env, s conversion.Scope) error {
	out.Approval = in.Approval
	out.Replicas = in.Replicas
	out.Variables = *(*[]app.Variable)(unsafe.Pointer(&in.Variables))
	out.KubernetesName = in.KubernetesName
	out.KubernetesNamespace = in.KubernetesNamespace
	out.ConfigMap = *(*map[string]string)(unsafe.Pointer(&in.ConfigMap))
	out.ConfigMountPath = in.ConfigMountPath
	return nil
}

// Convert_v1_Env_To_app_Env is an autogenerated conversion function.
func Convert_v1_Env_To_app_Env(in *Env, out *app.Env, s conversion.Scope) error {
	return autoConvert_v1_Env_To_app_Env(in, out, s)
}

func autoConvert_app_Env_To_v1_Env(in *app.Env, out *Env, s conversion.Scope) error {
	out.Approval = in.Approval
	out.Replicas = in.Replicas
	out.Variables = *(*[]Variable)(unsafe.Pointer(&in.Variables))
	out.KubernetesName = in.KubernetesName
	out.KubernetesNamespace = in.KubernetesNamespace
	out.ConfigMap = *(*map[string]string)(unsafe.Pointer(&in.ConfigMap))
	out.ConfigMountPath = in.ConfigMountPath
	return nil
}

// Convert_app_Env_To_v1_Env is an autogenerated conversion function.
func Convert_app_Env_To_v1_Env(in *app.Env, out *Env, s conversion.Scope) error {
	return autoConvert_app_Env_To_v1_Env(in, out, s)
}

func autoConvert_v1_Port_To_app_Port(in *Port, out *app.Port, s conversion.Scope) error {
	out.Name = in.Name
	out.Port = in.Port
	out.TargetPort = in.TargetPort
	return nil
}

// Convert_v1_Port_To_app_Port is an autogenerated conversion function.
func Convert_v1_Port_To_app_Port(in *Port, out *app.Port, s conversion.Scope) error {
	return autoConvert_v1_Port_To_app_Port(in, out, s)
}

func autoConvert_app_Port_To_v1_Port(in *app.Port, out *Port, s conversion.Scope) error {
	out.Name = in.Name
	out.Port = in.Port
	out.TargetPort = in.TargetPort
	return nil
}

// Convert_app_Port_To_v1_Port is an autogenerated conversion function.
func Convert_app_Port_To_v1_Port(in *app.Port, out *Port, s conversion.Scope) error {
	return autoConvert_app_Port_To_v1_Port(in, out, s)
}

func autoConvert_v1_Product_To_app_Product(in *Product, out *app.Product, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_ProductSpec_To_app_ProductSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_ProductStatus_To_app_ProductStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_Product_To_app_Product is an autogenerated conversion function.
func Convert_v1_Product_To_app_Product(in *Product, out *app.Product, s conversion.Scope) error {
	return autoConvert_v1_Product_To_app_Product(in, out, s)
}

func autoConvert_app_Product_To_v1_Product(in *app.Product, out *Product, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_app_ProductSpec_To_v1_ProductSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_app_ProductStatus_To_v1_ProductStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_app_Product_To_v1_Product is an autogenerated conversion function.
func Convert_app_Product_To_v1_Product(in *app.Product, out *Product, s conversion.Scope) error {
	return autoConvert_app_Product_To_v1_Product(in, out, s)
}

func autoConvert_v1_ProductList_To_app_ProductList(in *ProductList, out *app.ProductList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]app.Product)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_ProductList_To_app_ProductList is an autogenerated conversion function.
func Convert_v1_ProductList_To_app_ProductList(in *ProductList, out *app.ProductList, s conversion.Scope) error {
	return autoConvert_v1_ProductList_To_app_ProductList(in, out, s)
}

func autoConvert_app_ProductList_To_v1_ProductList(in *app.ProductList, out *ProductList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Product)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_app_ProductList_To_v1_ProductList is an autogenerated conversion function.
func Convert_app_ProductList_To_v1_ProductList(in *app.ProductList, out *ProductList, s conversion.Scope) error {
	return autoConvert_app_ProductList_To_v1_ProductList(in, out, s)
}

func autoConvert_v1_ProductSpec_To_app_ProductSpec(in *ProductSpec, out *app.ProductSpec, s conversion.Scope) error {
	out.Owner = in.Owner
	return nil
}

// Convert_v1_ProductSpec_To_app_ProductSpec is an autogenerated conversion function.
func Convert_v1_ProductSpec_To_app_ProductSpec(in *ProductSpec, out *app.ProductSpec, s conversion.Scope) error {
	return autoConvert_v1_ProductSpec_To_app_ProductSpec(in, out, s)
}

func autoConvert_app_ProductSpec_To_v1_ProductSpec(in *app.ProductSpec, out *ProductSpec, s conversion.Scope) error {
	out.Owner = in.Owner
	return nil
}

// Convert_app_ProductSpec_To_v1_ProductSpec is an autogenerated conversion function.
func Convert_app_ProductSpec_To_v1_ProductSpec(in *app.ProductSpec, out *ProductSpec, s conversion.Scope) error {
	return autoConvert_app_ProductSpec_To_v1_ProductSpec(in, out, s)
}

func autoConvert_v1_ProductStatus_To_app_ProductStatus(in *ProductStatus, out *app.ProductStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1_ProductStatus_To_app_ProductStatus is an autogenerated conversion function.
func Convert_v1_ProductStatus_To_app_ProductStatus(in *ProductStatus, out *app.ProductStatus, s conversion.Scope) error {
	return autoConvert_v1_ProductStatus_To_app_ProductStatus(in, out, s)
}

func autoConvert_app_ProductStatus_To_v1_ProductStatus(in *app.ProductStatus, out *ProductStatus, s conversion.Scope) error {
	return nil
}

// Convert_app_ProductStatus_To_v1_ProductStatus is an autogenerated conversion function.
func Convert_app_ProductStatus_To_v1_ProductStatus(in *app.ProductStatus, out *ProductStatus, s conversion.Scope) error {
	return autoConvert_app_ProductStatus_To_v1_ProductStatus(in, out, s)
}

func autoConvert_v1_Variable_To_app_Variable(in *Variable, out *app.Variable, s conversion.Scope) error {
	out.Key = in.Key
	out.Value = in.Value
	return nil
}

// Convert_v1_Variable_To_app_Variable is an autogenerated conversion function.
func Convert_v1_Variable_To_app_Variable(in *Variable, out *app.Variable, s conversion.Scope) error {
	return autoConvert_v1_Variable_To_app_Variable(in, out, s)
}

func autoConvert_app_Variable_To_v1_Variable(in *app.Variable, out *Variable, s conversion.Scope) error {
	out.Key = in.Key
	out.Value = in.Value
	return nil
}

// Convert_app_Variable_To_v1_Variable is an autogenerated conversion function.
func Convert_app_Variable_To_v1_Variable(in *app.Variable, out *Variable, s conversion.Scope) error {
	return autoConvert_app_Variable_To_v1_Variable(in, out, s)
}
